### PR TITLE
build: fix style of template and build backend requests for personalInfo and motivation sections

### LINKED ISSUE #34: DatePicker present option doesn't save it's value if go back to its section

### LINKED ISSUE #35: Backend development for the candidate interface

### LINKED ISSUE #36: For cards sections make a simple review after the user is done editing the card

### LINKED ISSUE #38: Validate uploading data

### LINKED ISSUE #39: Group the buttons for spacing

### LINKED ISSUE #40: Modify the sections input layout

### LINKED ISSUE #41: Disable saving the appData if there is no differences between the state and the appData “or view a toast message of the saving success”

### LINKED ISSUE #42: Title for each section should be mentioned before the explanation paragraph

### LINKED ISSUE #43: Show the entered skills in the little review as chips components instead of plain text

### LINKED ISSUE #44: Make the steps on the stepper accessible for the user to easy access the sections

### LINKED ISSUE #45: Handle the values of Cv object and structure them using appData

### PR DESCRIPTION
**Pull request by AmeerTawfik**
This PR also fixes:
1. closes #34 
2. closes #35 
3. closes #36 
4. closes #40 
5. closes #39 
6. closes #41 
7. closes #42 
8. closes #43 
9. closes #38 
10. closes #44 
11. closes #45

### CODE REVIEW

**Comment by AmeerTawfik** [comment]
Solving the following issue:
#34

**Comment by AmeerTawfik** [comment]
Solving the following issue:
#36

File: src/components/views/read/cvForm/Education.tsx [hunk 1]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable @typescript-eslint/no-unused-vars */
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:1]: Remove this and try to fix the lint issue. In case you need to disable the rule, it would be better to do so for only the specific line. Disabling it for the whole file is not a good practice.

File: src/components/views/read/cvForm/Education.tsx [hunk 2]
```diff
@@ -36,14 +38,27 @@ const Education: FC<Props> = ({
   educationData,
   onCvValuesChange,
 }) => {
+  const { postAppData, patchAppData, deleteAppData, appDataArray } =
+    useAppDataContext();
+  const educationInfoObject = appDataArray.find(
+    (obj) => obj.type === 'educationInfo',
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:44]: Good ! It would be nice if you refactored this type to a constant. How about `const EDUCATION_APP_DATA_TYPE = "educationInfo";` ?

Or even better, define an object to group your appData types together:
```ts
const APP_DATA_TYPES = {
  EDUCATION: 'educationInfo',
  ...
};
```

File: src/components/views/read/cvForm/Education.tsx [hunk 3]
```diff
@@ -36,14 +38,27 @@ const Education: FC<Props> = ({
...
+  );
+  const handlePost = (newdata: EducationInfoObj): void => {
+    postAppData({ data: newdata, type: 'educationInfo' });
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:47]: Use the constant for the type here.

File: src/components/views/read/cvForm/Education.tsx [hunk 4]
```diff
@@ -36,14 +38,27 @@ const Education: FC<Props> = ({
...
+  };
+  const handlePatch = (dataObj: any, newData: EducationInfoObj): void => {
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:49]: Do not use any, I am guessing you would receive the appData here, which has type: `AppData`.

File: src/components/views/read/cvForm/Education.tsx [hunk 5]
```diff
@@ -36,14 +38,27 @@ const Education: FC<Props> = ({
...
+    patchAppData({ id: dataObj.id, data: newData });
+  };
+  const handleDelete = (dataObj: any): void => {
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:52]: Same here, do not use `any`.

File: src/components/views/read/cvForm/Education.tsx [hunk 6]
```diff
@@ -89,6 +101,26 @@ const Education: FC<Props> = ({
   };
 
   const handleDone = (cardId: string): void => {
+    const educationWithoutPresent = educationCards.map(
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:104]: I am not convinced by your handling of the present inside the card...

File: src/components/views/read/cvForm/Education.tsx [hunk 7]
```diff
@@ -97,6 +129,12 @@ const Education: FC<Props> = ({
   };
 
   const handleRemove = (cardId: string): void => {
+    const objToDelete = appDataArray.filter(
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:132]: This already exists under the `educationInfoObj` variable, why re-define it here ?

File: src/components/views/read/cvForm/Education.tsx [hunk 8]
```diff
@@ -116,12 +158,18 @@ const Education: FC<Props> = ({
     });
   };
   const handlePrev = (): void => {
-    onCvValuesChange(educationCards);
+    const educationWithoutPresent = educationCards.map(
+      ({ present, ...rest }) => rest,
+    );
+    onCvValuesChange(educationWithoutPresent);
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:164]: I don't think you need this anymore, as all the values are coming form the appDataArray. If they are not in there, they are not saved so there is no point.

File: src/components/views/read/cvForm/Education.tsx [hunk 9]
```diff
@@ -116,12 +158,18 @@ const Education: FC<Props> = ({
...
     prevPage();
     prevStep();
   };
   const handleNext = (): void => {
-    onCvValuesChange(educationCards);
+    const educationWithoutPresent = educationCards.map(
+      ({ present, ...rest }) => rest,
+    );
+    onCvValuesChange(educationWithoutPresent);
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:172]: Same.

**Review by spaenleh — COMMENTED** [review]
Good start, I only reviewed `Education` but comments apply to all others. 
I think there is in general a lot of duplication between your components that handle cards. The content may not be the same, but the logic around is _exactly_ the same. It may be worth trying to but that logic into a component. We can discuss that. 

Regarding the implementation, I think we can still work on it to improve it. What is the status of the development currently ? Is this working to save data, if the data retrieved when going back ?

**Comment by spaenleh** [comment]
@AmeerTawfik About issue #34 I think it should be solved differently.
The main issue is that the value for the endDate is not given correctly in the case where `endDate = 'OnGoing'`.
https://github.com/graasp/graasp-app-cv-tools/blob/7946529374e1f20215d9bbf7493566c396746380/src/components/views/read/cvForm/Education.tsx#L226
```ts
value={card.endDate && card.endDate !== "OnGoing" ? dayjs(card.endDate) : undefined}
```
And for the value of the checkbox, it should be infered from the endDate.
https://github.com/graasp/graasp-app-cv-tools/blob/7946529374e1f20215d9bbf7493566c396746380/src/components/views/read/cvForm/Education.tsx#L240
```ts
checked={card.endDate === "OnGoing"}
```

File: src/config/appDataTypes.ts [hunk 10]
```diff
@@ -1,5 +1,13 @@
 enum APP_DATA_TYPES {
   MOCK_TYPE = 'mock_type',
+  PERSONALINFO = 'personalInfo',
+  EDUCATION = 'educationInfo',
+  WORKEXPERIENCE = 'workInfo',
+  SKILLS = 'skillsInfo',
+  PORTFOLIO = 'portfolioInfo',
+  MOTIVATION = 'motivationInfo',
+  REFERENCES = 'referencesInfo',
+  TMEPLATE = 'templateInfo',
```
Comment (spaenleh) [inline src/config/appDataTypes.ts:10]:
```suggestion
  TEMPLATE = 'templateInfo',
```

**Comment by AmeerTawfik** [comment]
Solve the following issue:
#40

**Comment by AmeerTawfik** [comment]
Solve the following issue:
#41

**Comment by AmeerTawfik** [comment]
Solve the following issue:
#43

**Comment by AmeerTawfik** [comment]
Solve the following issue, but needs more modification to show the toast message as it doesn't work:
#38

**Comment by AmeerTawfik** [comment]
Solve the following issue:
#44

**Comment by AmeerTawfik** [comment]
Solving the following issue: 
#45

**Comment by AmeerTawfik** [comment]
Solve the following issue: 
#44

File: src/config/appDataTypes.ts [hunk 11]
```diff
@@ -1,5 +1,15 @@
 enum APP_DATA_TYPES {
   MOCK_TYPE = 'mock_type',
+  PERSONALINFO = 'personalInfo',
+  EDUCATION = 'educationInfo',
+  WORKEXPERIENCE = 'workInfo',
+  SKILLS = 'skillsInfo',
+  PORTFOLIO = 'portfolioInfo',
+  MOTIVATION = 'motivationInfo',
+  REFERENCES = 'referencesInfo',
+  CVSTATUSDATA = 'cvStateInfo',
```
Comment (spaenleh) [inline src/config/appDataTypes.ts:10]: Try to make the naming consistant, `PERSONAL_INFO`, `EDUCATION_INFO` etc ...

**Review by spaenleh — CHANGES_REQUESTED** [review]
Thank you for these changes ! Have a look at my comments, I like to see the validations and the nice touches on the better layout of the buttons and the sections ! This is really coming together !

File: src/components/views/read/cvForm/PersonalInfo.tsx [hunk 12]
```diff
@@ -131,79 +197,201 @@ const PersonalInfo: FC<Props> = ({
     setVisibility(!visibility);
   };
 
+  const handleSave = (): void => {
```
[the remark this answers is not in the document]
Comment (AmeerTawfik) [reply src/components/views/read/cvForm/PersonalInfo.tsx:205]: I will open a new issue for the validation to use Vest library for the validation.

File: src/components/views/read/cvForm/Cv.tsx [hunk 13]
```diff
@@ -0,0 +1,388 @@
...
+    }
+    nextStep();
+  };
+
+  return (
+    <Box>
+      <Typography sx={{ m: '0.5rem' }}>
+        For this part you can either pickup and select the template that you
+        would like to have on your CV applied on the information you provided in
+        the previous sections, by making sure the &quot;Generated CV&quot; is
```
[the remark this answers is not in the document]
Comment (AmeerTawfik) [reply src/components/views/read/cvForm/Cv.tsx:285]: It will show a eslint error, if i used the normal quotes.

[the remark this answers is not in the document]
Comment (spaenleh) [reply src/components/views/read/cvForm/Cv.tsx:285]: Okay, it most likely is a false positive. Can you try putting the text in a constant and using that constant here instead. The next step will be to add translations to all the app text, so you could also do that. You would only need to add the text to the `lang/en.json` file.

[the remark this answers is not in the document]
Comment (AmeerTawfik) [reply src/components/views/read/cvForm/Cv.tsx:285]: Ok, great. do you think as a suggestion to solve this one "and some other conversations still not resolved" in a new issue  and PR, Ig it's the time to clost this PR and start cleaner PR :)

File: src/components/views/read/cvForm/PersonalInfo.tsx [hunk 14]
```diff
@@ -90,39 +93,102 @@ const PersonalInfo: FC<Props> = ({
...
+      }));
+    } else {
+      const value = (personalInfoState as AppData & { data: PersonalInfoObj })
+        .data[key] as string;
+      if (!value.trim()) {
+        setErrors((prevErrors) => ({
+          ...prevErrors,
+          [key]: `${label} is required`,
+        }));
+      }
```
[the remark this answers is not in the document]
Comment (AmeerTawfik) [reply src/components/views/read/cvForm/PersonalInfo.tsx]: The goal is to set the error message, and the conditions is supposed to handle, so I will re-construct the condition to shorten it without this messy and duplicated one :)

File: src/components/views/read/cvForm/Cv.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (spaenleh) [reply src/components/views/read/cvForm/Cv.tsx:285]: Yes you can open an issue for that. I will make a final review of the PR.

File: src/components/views/read/cvForm/Home.tsx [hunk 15]
```diff
@@ -1,7 +1,8 @@
 import { ChangeEvent, FC, RefObject, useRef } from 'react';
 
-import { AppData } from '@graasp/apps-query-client/dist/types';
+import { AppData } from '@graasp/apps-query-client';
 
+// toastcontainer in the app comp, and the css styles
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Home.tsx:5]: Remove.

File: src/config/appDataTypes.ts [hunk 16]
```diff
@@ -1,13 +1,13 @@
...
-  REFERENCES = 'referencesInfo',
-  CVSTATUSDATA = 'cvStateInfo',
+  PERSONAL_INFO = 'personalInfo',
+  EDUCATION_INFO = 'educationInfo',
+  WORK_EXPERIENCE_INFO = 'workInfo',
+  SKILLS_INFO = 'skillsInfo',
+  PROJECTS_INFO = 'projectsInfo',
+  MOTIVATION_INFO = 'motivationInfo',
+  REFERENCES_INFO = 'referencesInfo',
+  CV_STATUS_DATA = 'cvStatusInfo',
```
Comment (spaenleh) [inline src/config/appDataTypes.ts:10]: Would you like to use `CV_STATUS_INFO` for coherence ?

**Review by spaenleh — CHANGES_REQUESTED** [review]
Looks good, just a few comments to remove. 
You also have some ButtonGroups that need to be converted to Stacks.
And we will be good to go !

File: src/components/views/read/cvForm/Cv.tsx [hunk 17]
```diff
@@ -211,58 +211,48 @@ const Template: FC<Props> = ({ nextStep, prevStep }) => {
...
   );
 
-  const educationDataArray: Data[] = [];
-  educationInfoObject.map((card) => {
-    educationDataArray.push(card.data);
-    return null;
-  });
+  const educationDataArray = educationInfoObject.map(
+    (card) => card.data,
+  ) as unknown as EducationInfoObj[];
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Cv.tsx:216]: Your casting to unknown is an clue to the fact that it is not what you want. I think you meant:
```suggestion
  const educationDataArray = educationInfoObject.map(
    (card) => card.data as EducationInfoObj,
  );
```

File: src/components/views/read/cvForm/Education.tsx [hunk 18]
```diff
@@ -277,6 +277,7 @@ const Education: FC<Props> = ({ nextStep, prevStep }) => {
     { key: 'gpa', label: 'GPA' },
     { key: 'country', label: 'Country' },
   ];
+  const onGoing = 'OnGoing';
```
Comment (spaenleh) [inline src/components/views/read/cvForm/Education.tsx:280]: This can be a global constant, as you use it in multiple components.

**Review by spaenleh — COMMENTED** [review]
Yes ! very close, just a few nitpicks on typing.

File: src/components/views/read/cvForm/Cv.tsx (hunk 17 above)
Comment (AmeerTawfik) [reply src/components/views/read/cvForm/Cv.tsx:216]: I tried that actually, and If i set that again to be like that it will get this error:
```
Conversion of type 'List<Data>' to type 'EducationInfoObj' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'List<Data>' is missing the following properties from type 'EducationInfoObj': id, degree, institutionName, major, and 5 more.ts(2352)
const educationInfoObject: Immutable.List<AppData>
```

Comment (spaenleh) [reply src/components/views/read/cvForm/Cv.tsx:216]: Yes this is why you need to cast it **inside** the map. The issue is that you are getting an Immutable.List which not the same as an Array (`[]`) but they have the same API, so `.map` exists on both. Check my suggestion again.

**Review by spaenleh — APPROVED** [review]
👍
